<?php

namespace AppBundle\Entity;

use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findApi($id = null)
    {
        $qb = $this->createQueryBuilder('c');

        if( null !== $id){
            $qb
                ->where('c.id = :id')
                ->setParameter(':id', $id)
            ;
        }

        return  null === $id ? $qb->getQuery()->getArrayResult() : $qb->getQuery()->getSingleResult(AbstractQuery::HYDRATE_ARRAY);
    }
}
